### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Thirumalai-Shaktivel** [ComPy-Lang/ComPy#2]
#### March
- [x] Add Libasr from LFortran
- [x] Add ASR Grammar from libasr
- [x] Add initial CMake Support
- [x] Build the project using CMake
#### April
- [x] Implement Tokenizer
- [x] Design new Syntax for ComPy
- [x] Implement Parser
- [x] Add AST grammar
#### May
- [x] Convert AST to ASR
- [x] Convert ASR to LLVM
- [x] Compile to Binaries
#### June
- [x] Benchmark
  - [x]  Count the Prime Numbers
  - [x] Fibonacci
  - [ ] Tower of Honai
  - [x] Sorting algorithm (Quick Sort)
  - [ ] e power computations
